### ISSUE TITLE
Crash when clicking blank canvas

### ISSUE THREAD

**Issue by codefaux** [ahrm/UnstableFusion#20]
Just as listed - start the app, click the blank window anywhere. App freezes, app explodes. Implodes? Anyway, lol

Current commit is b7ae99059f984050061773602f7db328540ffd50 (If I did that right)

```Traceback (most recent call last):
  File "C:\Code\git\UnstableFusion\unstablefusion.py", line 633, in mousePressEvent
    pos = self.window_to_image_point(e.pos())
  File "C:\Code\git\UnstableFusion\unstablefusion.py", line 660, in window_to_image_point
    return QPoint(new_x, new_y)
TypeError: arguments did not match any overloaded call:
  QPoint(): too many arguments
  QPoint(int, int): argument 1 has unexpected type 'float'
  QPoint(QPoint): argument 1 has unexpected type 'float'```

**Comment by ahrm** [comment]
Should be fixed now.

**Comment by codefaux** [comment]
lol what took so long :P

Seriously though, impressive response time, good fix. Can't wait to experiment with it.
