### ISSUE TITLE
Crash when loading modifiers without previously saving them

### ISSUE THREAD

**Issue by ZapExp** [ahrm/UnstableFusion#22]
If you click the "Load Modifiers" button before saving them the app crashes, I got the following error in console:

```
Traceback (most recent call last):
  File "C:\Users\davic\Desktop\AI\UnstableFusion\unstablefusion.py", line 1129, in handle_load_modifiers
    mods = load_modifiers()
  File "C:\Users\davic\Desktop\AI\UnstableFusion\unstablefusion.py", line 51, in load_modifiers
    with open(get_modifiers_path(), 'r') as infile:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\davic\\Desktop\\AI\\UnstableFusion\\modifiers.txt'
```

**Comment by ahrm** [comment]
Should be fixed in bd43e1a1b54053746f1ca7ddfa22f65e531adbde.
