### ISSUE TITLE
Any prompt "Torch not compiled with CUDA enabled"

### ISSUE THREAD

**Issue by ffdown** [ahrm/UnstableFusion#29]
Fetching 16 files: 100%|█████████████████████████████████████████████████████████████| 16/16 [00:00<00:00, 3181.27it/s]
Traceback (most recent call last):
  File "unstablefusion.py", line 889, in handle_inpaint_button
    inpainted_image = self.get_handler().inpaint(prompt,
  File "unstablefusion.py", line 436, in get_handler
    return self.stable_diffusion_manager.get_handler()
  File "unstablefusion.py", line 318, in get_handler
    return self.get_local_handler(self.get_huggingface_token())
  File "unstablefusion.py", line 301, in get_local_handler
    self.cached_local_handler = StableDiffusionHandler(token)
  File "E:\AI\SD\SDUI\UnstableFusion-main\diffusionserver.py", line 27, in __init__
    self.text2img = StableDiffusionPipeline.from_pretrained(
  File "e:\Anaconda3\envs\ldm\lib\site-packages\diffusers\pipeline_utils.py", line 179, in to
    module.to(torch_device)
  File "e:\Anaconda3\envs\ldm\lib\site-packages\torch\nn\modules\module.py", line 907, in to
    return self._apply(convert)
  File "e:\Anaconda3\envs\ldm\lib\site-packages\torch\nn\modules\module.py", line 578, in _apply
    module._apply(fn)
  File "e:\Anaconda3\envs\ldm\lib\site-packages\torch\nn\modules\module.py", line 578, in _apply
    module._apply(fn)
  File "e:\Anaconda3\envs\ldm\lib\site-packages\torch\nn\modules\module.py", line 578, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "e:\Anaconda3\envs\ldm\lib\site-packages\torch\nn\modules\module.py", line 601, in _apply
    param_applied = fn(param)
  File "e:\Anaconda3\envs\ldm\lib\site-packages\torch\nn\modules\module.py", line 905, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "e:\Anaconda3\envs\ldm\lib\site-packages\torch\cuda\__init__.py", line 210, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by ahrm** [comment]
As the title suggests, you need to install pytorch with cuda enabled (after installing cuda itself of course).

**Comment by ffdown** [comment]
cuda installed, pytorch too... I don't understand anything( automatic111 works fine

**Comment by ahrm** [comment]
It is not enough for pytorch and cuda to be installed. **You need to install the cuda version of pytorch**. Automatic111 creates its own virtual environment, so it doesn't affect your global python installation.

**Comment by ffdown** [comment]
command for conda please, anyone combination  not work

**Comment by Apatiste** [comment]
I have the exact same issue, it's saddening that no ones is helping 
https://www.youtube.com/watch?v=GMSjDTU8Zlc&list=LL&index=1 

I have cuda, pytorch, and the Pytorch's version of cuda installed, and yet I run into the exact same issue  

   raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by ahrm** [comment]
In order to test if you have pytorch with cuda available, you can run the `python` command and then enter:
```
import torch
print(torch.cuda.is_available())
```

Note that the tutorial video that you linked creates a virtual environment, so you only have torch within that virtual environment.

**Comment by Apatiste** [comment]
> In order to test if you have pytorch with cuda available, you can run the `python` command and then enter:
> 
> ```
> import torch
> print(torch.cuda.is_available())
> ```
> 
> Note that the tutorial video that you linked creates a virtual environment, so you only have torch within that virtual environment.

Oh my bad, it's indeed telling me that cuda isn't installed while running this command 

How do you install cuda for pytorch that can be used anywhere ?

**Comment by ahrm** [comment]
Don't create a new environment, install it globally, or alternatively you can switch to the environment that you created in visual studio and presumably already has torch installed.

**Comment by Apatiste** [comment]
I've just installed it globally, and I still run into the same issue, it appears fine in the pip list command too

**Comment by Apatiste** [comment]
Ok so I've just found out I had the cpu version installed while running the print(torch.__version__) command for whatever reason, I will try uninstalling it and re install the gpu one

**Comment by calebrader** [comment]
> It is not enough for pytorch and cuda to be installed. **You need to install the cuda version of pytorch**. Automatic111 creates its own virtual environment, so it doesn't affect your global python installation.

How do you do that? Please give pip or conda examples.
