### ISSUE TITLE
Getting this error when I try to generate an image. I'm on arch linux.

### ISSUE THREAD

**Issue by PistachioGuy** [ahrm/UnstableFusion#39]
Traceback (most recent call last):
  File "/home/boi/.local/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 213, in hf_raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/fp16/model_index.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/boi/.local/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 228, in get_config_dict
    config_file = hf_hub_download(
  File "/home/boi/.local/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1053, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "/home/boi/.local/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1359, in get_hf_file_metadata
    hf_raise_for_status(r)
  File "/home/boi/.local/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 254, in hf_raise_for_status
    raise HfHubHTTPError(str(HTTPError), response=response) from e
huggingface_hub.utils._errors.HfHubHTTPError: <class 'requests.exceptions.HTTPError'> (Request ID: Nk1158C9LHrkTH1ybJVBC)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/boi/UnstableFusion/unstablefusion.py", line 897, in handle_generate_button
    if type(self.get_handler()) == ServerStableDiffusionHandler:
  File "/home/boi/UnstableFusion/unstablefusion.py", line 460, in get_handler
    return self.stable_diffusion_manager.get_handler()
  File "/home/boi/UnstableFusion/unstablefusion.py", line 329, in get_handler
    return self.get_local_handler(self.get_huggingface_token())
  File "/home/boi/UnstableFusion/unstablefusion.py", line 312, in get_local_handler
    self.cached_local_handler = StableDiffusionHandler(token)
  File "/home/boi/UnstableFusion/diffusionserver.py", line 33, in __init__
    self.text2img = StableDiffusionPipeline.from_pretrained(
  File "/home/boi/.local/lib/python3.10/site-packages/diffusers/pipeline_utils.py", line 431, in from_pretrained
    config_dict = cls.get_config_dict(
  File "/home/boi/.local/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 260, in get_config_dict
    raise EnvironmentError(
OSError: There was a specific connection error when trying to load runwayml/stable-diffusion-v1-5:
<class 'requests.exceptions.HTTPError'> (Request ID: Nk1158C9LHrkTH1ybJVBC)

**Comment by ahrm** [comment]
You need to accept the license agreement in the model's page here:
https://huggingface.co/runwayml/stable-diffusion-v1-5

**Comment by PistachioGuy** [comment]
Thank you, that fixed it. But not it says i need cuda, is it at all possible to use this on an AMD gpu or do i need nvidia?

**Comment by ahrm** [comment]
You need nvidia (you can run the server on a google colba though).

**Comment by PistachioGuy** [comment]
So i would have to host it on a nvidia device? or are there any existing servers i can use?

**Comment by ahrm** [comment]
Yes, there is documentation here: https://github.com/ahrm/UnstableFusion#how-to-run-using-colab-servers

**Comment by ahrm** [comment]
Should be fixed in the latest commits.

**Comment by PistachioGuy** [comment]
I'll try it, thanks.
