### ISSUE TITLE
TypeError: Descriptors cannot not be created directly.

### ISSUE THREAD

**Issue by ZeroCool22** [ahrm/UnstableFusion#4]
```
C:\Users\ZeroCool22\Desktop\UnstableFusion\UnstableFusion>python unstablefusion.py
Traceback (most recent call last):
  File "C:\Users\ZeroCool22\Desktop\UnstableFusion\UnstableFusion\unstablefusion.py", line 7, in <module>
    from diffusionserver import StableDiffusionHandler
  File "C:\Users\ZeroCool22\Desktop\UnstableFusion\UnstableFusion\diffusionserver.py", line 4, in <module>
    from diffusers import StableDiffusionPipeline, StableDiffusionInpaintPipeline, StableDiffusionImg2ImgPipeline
  File "C:\Users\ZeroCool22\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\__init__.py", line 26, in <module>
    from .pipelines import DDIMPipeline, DDPMPipeline, KarrasVePipeline, LDMPipeline, PNDMPipeline, ScoreSdeVePipeline
  File "C:\Users\ZeroCool22\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\pipelines\__init__.py", line 11, in <module>
    from .latent_diffusion import LDMTextToImagePipeline
  File "C:\Users\ZeroCool22\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\pipelines\latent_diffusion\__init__.py", line 6, in <module>
    from .pipeline_latent_diffusion import LDMBertModel, LDMTextToImagePipeline
  File "C:\Users\ZeroCool22\AppData\Local\Programs\Python\Python310\lib\site-packages\diffusers\pipelines\latent_diffusion\pipeline_latent_diffusion.py", line 12, in <module>
    from transformers.modeling_utils import PreTrainedModel
  File "C:\Users\ZeroCool22\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\modeling_utils.py", line 75, in <module>
    from accelerate import __version__ as accelerate_version
  File "C:\Users\ZeroCool22\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\__init__.py", line 7, in <module>
    from .accelerator import Accelerator
  File "C:\Users\ZeroCool22\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\accelerator.py", line 33, in <module>
    from .tracking import LOGGER_TYPE_TO_CLASS, GeneralTracker, filter_trackers
  File "C:\Users\ZeroCool22\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\tracking.py", line 34, in <module>
    import wandb
  File "C:\Users\ZeroCool22\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\__init__.py", line 26, in <module>
    from wandb import sdk as wandb_sdk
  File "C:\Users\ZeroCool22\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\__init__.py", line 9, in <module>
    from .wandb_init import _attach, init  # noqa: F401
  File "C:\Users\ZeroCool22\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\wandb_init.py", line 30, in <module>
    from . import wandb_login, wandb_setup
  File "C:\Users\ZeroCool22\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\wandb_login.py", line 25, in <module>
    from .wandb_settings import Settings, Source
  File "C:\Users\ZeroCool22\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\wandb_settings.py", line 39, in <module>
    from wandb.sdk.wandb_setup import _EarlyLogger
  File "C:\Users\ZeroCool22\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\wandb_setup.py", line 22, in <module>
    from . import wandb_manager, wandb_settings
  File "C:\Users\ZeroCool22\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\wandb_manager.py", line 14, in <module>
    from wandb.sdk.lib.proto_util import settings_dict_from_pbmap
  File "C:\Users\ZeroCool22\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\lib\proto_util.py", line 6, in <module>
    from wandb.proto import wandb_internal_pb2 as pb
  File "C:\Users\ZeroCool22\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\proto\wandb_internal_pb2.py", line 15, in <module>
    from wandb.proto import wandb_base_pb2 as wandb_dot_proto_dot_wandb__base__pb2
  File "C:\Users\ZeroCool22\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\proto\wandb_base_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "C:\Users\ZeroCool22\AppData\Local\Programs\Python\Python310\lib\site-packages\google\protobuf\descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

C:\Users\ZeroCool22\Desktop\UnstableFusion\UnstableFusion>
```

**Comment by ahrm** [comment]
Try `pip install protobuf` and see if the issue persists.

**Comment by ZeroCool22** [comment]
> Try `pip install protobuf` and see if the issue persists.

![Screenshot_27](https://user-images.githubusercontent.com/13344308/191958254-dca1d014-a831-4f26-bfaf-844ad755b291.jpg)

Say it's already installed, but i get same error.... :(

**Comment by ahrm** [comment]
Maybe try `pip install protobuf==4.21.6`?

**Comment by ZeroCool22** [comment]
> Maybe try `pip install protobuf==4.21.6`?

```
C:\Users\ZeroCool22\Desktop\UnstableFusion\UnstableFusion>pip install protobuf==4.21.6
Requirement already satisfied: protobuf==4.21.6 in c:\users\zerocool22\appdata\local\programs\python\python310\lib\site-packages (4.21.6)
```

**Comment by ZeroCool22** [comment]
Should i downgrade version as the message said?

**Comment by ahrm** [comment]
It may be worth a try. But I have `4.21.6` myself.

**Comment by ahrm** [comment]
I think the issue might more likely be your other packages being outdated. Make sure your packages meet the minimum version in requirements.txt here: https://github.com/ahrm/UnstableFusion/blob/main/requirements.txt .

**Comment by ZeroCool22** [comment]
> I think the issue might more likely be your other packages being outdated. Make sure your packages meet the minimum version in requirements.txt here: https://github.com/ahrm/UnstableFusion/blob/main/requirements.txt .

I downgraded and now i get a different error:

C:```
\Users\ZeroCool22\Desktop\UnstableFusion\UnstableFusion>pip install --force-reinstall protobuf==3.20.1
Collecting protobuf==3.20.1
  Using cached protobuf-3.20.1-cp310-cp310-win_amd64.whl (903 kB)
Installing collected packages: protobuf
  Attempting uninstall: protobuf
    Found existing installation: protobuf 4.21.6
    Uninstalling protobuf-4.21.6:
      Successfully uninstalled protobuf-4.21.6
Successfully installed protobuf-3.20.1

C:\Users\ZeroCool22\Desktop\UnstableFusion\UnstableFusion>python unstablefusion.py
Traceback (most recent call last):
  File "C:\Users\ZeroCool22\Desktop\UnstableFusion\UnstableFusion\unstablefusion.py", line 936, in <module>
    strength_widget, strength_slider, strength_text = create_slider_widget(
  File "C:\Users\ZeroCool22\Desktop\UnstableFusion\UnstableFusion\unstablefusion.py", line 805, in create_slider_widget
    strength_slider.setValue(default * 100)
TypeError: setValue(self, int): argument 1 has unexpected type 'float'
```

**Comment by ZeroCool22** [comment]
> I think the issue might more likely be your other packages being outdated. Make sure your packages meet the minimum version in requirements.txt here: https://github.com/ahrm/UnstableFusion/blob/main/requirements.txt .

Yeah, i used the req.txt included on your repo when i cloned it.

**Comment by ahrm** [comment]
The new error should be fixed in the latest commits.

**Comment by ZeroCool22** [comment]
> The new error should be fixed in the latest commits.

Updated to last commit, but a new error now:

```
C:\Users\ZeroCool22\Desktop\UnstableFusion\UnstableFusion>python unstablefusion.py
Traceback (most recent call last):
  File "C:\Users\ZeroCool22\Desktop\UnstableFusion\UnstableFusion\unstablefusion.py", line 598, in paintEvent
    self.image_rect = QRect(offset_x, offset_y, w, h)
TypeError: arguments did not match any overloaded call:
  QRect(): too many arguments
  QRect(int, int, int, int): argument 1 has unexpected type 'float'
  QRect(QPoint, QPoint): argument 1 has unexpected type 'float'
  QRect(QPoint, QSize): argument 1 has unexpected type 'float'
  QRect(QRect): argument 1 has unexpected type 'float'

C:\Users\ZeroCool22\Desktop\UnstableFusion\UnstableFusion>
```

**Comment by ahrm** [comment]
It seems like the Qt version that you are using doesn't like float inputs. I will fix the issue soon, but I am curious on what is the version of your `PyQt5`?

**Comment by ZeroCool22** [comment]
> `PyQt5`

![Screenshot_30](https://user-images.githubusercontent.com/13344308/191967849-749399b3-659f-4a3e-9a42-c12fe469ef51.jpg)

**Comment by ahrm** [comment]
This issue should also be fixed in the latest commits. Please inform me if there are still issues (and thanks for your feedback, a lot of users seem to have similar issues to yours so your feedback is very helpful).

**Comment by ZeroCool22** [comment]
> This issue should also be fixed in the latest commits. Please inform me if there are still issues (and thanks for your feedback, a lot of users seem to have similar issues to yours so your feedback is very helpful).

Working!:

![Screenshot_31](https://user-images.githubusercontent.com/13344308/191969046-5a5627ba-a117-4d49-a407-7e5b572be4a0.jpg)

Just one doubt, using protobuf-**3.20**.1 instead the **last version** will affect me in some way, like more slow process or something?

**Comment by ahrm** [comment]
I don't think so.

**Comment by ZeroCool22** [comment]
> I don't think so.

Thx!
