### ISSUE TITLE
NameError: 'StableDiffusionHandler' is not defined

### ISSUE THREAD

**Issue by wyattjohnsonbro** [ahrm/UnstableFusion#40]
The full traceback is:
```
Traceback (most recent call last):
  File "/home/pokemon343638/UnstableFusion-main/unstablefusion.py", line 897, in handle_generate_button
    if type(self.get_handler()) == ServerStableDiffusionHandler:
  File "/home/pokemon343638/UnstableFusion-main/unstablefusion.py", line 460, in get_handler
    return self.stable_diffusion_manager.get_handler()
  File "/home/pokemon343638/UnstableFusion-main/unstablefusion.py", line 329, in get_handler
    return self.get_local_handler(self.get_huggingface_token())
  File "/home/pokemon343638/UnstableFusion-main/unstablefusion.py", line 312, in get_local_handler
    self.cached_local_handler = StableDiffusionHandler(token)
NameError: name 'StableDiffusionHandler' is not defined
```

**Comment by ahrm** [comment]
This should not happen, we import `StableDiffusionHandler` here:
```
try:
    from diffusionserver import StableDiffusionHandler
except ImportError:
    print(traceback.format_exc())
    print('Could not import StableDiffusionHandler, can not run locally')
```
So if there is a failure importing it, there should be a message on the output.
